"""
Import Diagnosis Data from Master List

This patch imports all diagnosis data (334 records) with:
- Diagnosis name, code, category
- Chronic/Acute classification
- Department, Severity, Follow-up days
- Billing code, Status
- Reportable and Notifiable flags
"""

import frappe


def execute():
    """Import Diagnosis data"""
    
    print("\n" + "="*60)
    print("Importing Diagnosis Data (334 Records)")
    print("="*60)
    
    # Get diagnosis data
    diagnosis_data = get_all_diagnosis_data()
    
    print(f"\n  Total records to process: {len(diagnosis_data)}")
    
    # Create Diagnosis Category if needed
    create_diagnosis_categories(diagnosis_data)
    
    # Import diagnoses
    import_diagnoses(diagnosis_data)
    
    frappe.db.commit()
    print("\n" + "="*60)
    print("✓ Diagnosis Data Import Completed!")
    print("="*60 + "\n")


def create_diagnosis_categories(diagnosis_data):
    """Create Diagnosis Categories from data"""
    
    print("\n--- Creating Diagnosis Categories ---")
    
    categories = set()
    for d in diagnosis_data:
        if d.get("diagnosis_category"):
            categories.add(d["diagnosis_category"])
    
    for cat in sorted(categories):
        if not frappe.db.exists("Diagnosis Category", cat):
            try:
                doc = frappe.new_doc("Diagnosis Category")
                doc.category_name = cat
                doc.is_active = 1
                doc.flags.ignore_permissions = True
                doc.insert()
                print(f"  ✓ Created: {cat}")
            except Exception as e:
                print(f"  - Error: {cat} - {str(e)}")
        else:
            print(f"  - Exists: {cat}")


def import_diagnoses(diagnosis_data):
    """Import diagnosis records"""
    
    print("\n--- Importing Diagnoses ---")
    
    created = 0
    updated = 0
    
    for d in diagnosis_data:
        diagnosis_name = d["diagnosis"]
        
        if frappe.db.exists("Diagnosis", diagnosis_name):
            try:
                doc = frappe.get_doc("Diagnosis", diagnosis_name)
                update_diagnosis_fields(doc, d)
                doc.flags.ignore_permissions = True
                doc.save()
                updated += 1
            except Exception as e:
                print(f"  ✗ Update error {diagnosis_name}: {str(e)[:50]}")
        else:
            try:
                doc = frappe.new_doc("Diagnosis")
                doc.diagnosis = diagnosis_name
                update_diagnosis_fields(doc, d)
                doc.flags.ignore_permissions = True
                doc.insert()
                created += 1
            except Exception as e:
                print(f"  ✗ Create error {diagnosis_name}: {str(e)[:50]}")
    
    print(f"\n  ✓ Created: {created}")
    print(f"  ✓ Updated: {updated}")
    print(f"  ✓ Total: {created + updated}")


def update_diagnosis_fields(doc, d):
    """Update diagnosis document fields"""
    doc.diagnosis_code = d.get("diagnosis_code", "")
    doc.chronic_or_acute = d.get("chronic_or_acute", "")
    doc.common_name = d.get("common_name", "")
    doc.synonyms = d.get("synonyms", "")
    doc.severity = d.get("severity", "")
    doc.default_follow_up_days = d.get("default_follow_up_days", 7)
    doc.billing_code = d.get("billing_code", "")
    doc.status = d.get("status", "Draft")
    doc.is_reportable = d.get("is_reportable", 0)
    doc.notifiable = d.get("notifiable", 0)
    
    if d.get("department") and frappe.db.exists("Medical Department", d["department"]):
        doc.department = d["department"]
    
    if d.get("diagnosis_category") and frappe.db.exists("Diagnosis Category", d["diagnosis_category"]):
        doc.diagnosis_category = d["diagnosis_category"]


def get_all_diagnosis_data():
    """Return all 333 diagnosis records from 3 parts"""
    from healthcare.patches.v15_0.diagnosis_data_part2 import get_data_part2
    from healthcare.patches.v15_0.diagnosis_data_part3 import get_data_part3
    
    # Part 1 data (inline below)
    part1 = [
        # Row 1-50
        {"diagnosis_code": "DIAG-0001", "chronic_or_acute": "Acute", "diagnosis_category": "Gastrointestinal", "diagnosis": "Cholera", "common_name": "Cholera", "synonyms": "Cholera", "icd11_code": "1A00", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00001", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0002", "chronic_or_acute": "Acute", "diagnosis_category": "Gastrointestinal", "diagnosis": "Typhoid fever", "common_name": "Typhoid fever", "synonyms": "Typhoid fever, Typhoid", "icd11_code": "1A04", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00002", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0003", "chronic_or_acute": "Acute", "diagnosis_category": "Medical Disease", "diagnosis": "Dengue", "common_name": "Dengue", "synonyms": "Dengue", "icd11_code": "1B10", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00003", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0004", "chronic_or_acute": "Acute", "diagnosis_category": "Medical Disease", "diagnosis": "COVID-19", "common_name": "COVID-19", "synonyms": "COVID-19", "icd11_code": "1C62", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00004", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0005", "chronic_or_acute": "Acute", "diagnosis_category": "Medical Disease", "diagnosis": "Influenza", "common_name": "Influenza", "synonyms": "Influenza", "icd11_code": "1C10", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00005", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0006", "chronic_or_acute": "Chronic", "diagnosis_category": "Respiratory", "diagnosis": "Pulmonary tuberculosis", "common_name": "Pulmonary tuberculosis", "synonyms": "Pulmonary tuberculosis, Pulmonary", "icd11_code": "1F40", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00006", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0007", "chronic_or_acute": "Acute", "diagnosis_category": "Medical Disease", "diagnosis": "Malaria", "common_name": "Malaria", "synonyms": "Malaria", "icd11_code": "1D47", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00007", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0008", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Type 2 diabetes mellitus", "common_name": "Type 2 diabetes mellitus", "synonyms": "Type 2 diabetes mellitus, Type", "icd11_code": "5A11", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00008", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0009", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Type 1 diabetes mellitus", "common_name": "Type 1 diabetes mellitus", "synonyms": "Type 1 diabetes mellitus, Type", "icd11_code": "5A10", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00009", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0010", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Hypothyroidism", "common_name": "Hypothyroidism", "synonyms": "Hypothyroidism", "icd11_code": "5A40", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00010", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0011", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Hyperthyroidism", "common_name": "Hyperthyroidism", "synonyms": "Hyperthyroidism", "icd11_code": "5A41", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00011", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0012", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Obesity", "common_name": "Obesity", "synonyms": "Obesity", "icd11_code": "5B81", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00012", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0013", "chronic_or_acute": "Chronic", "diagnosis_category": "Cardiovascular", "diagnosis": "Essential hypertension", "common_name": "Essential hypertension", "synonyms": "Essential hypertension, Essential", "icd11_code": "BA80", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00013", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0014", "chronic_or_acute": "Chronic", "diagnosis_category": "Cardiovascular", "diagnosis": "Ischaemic heart disease", "common_name": "Ischaemic heart disease", "synonyms": "Ischaemic heart disease, Ischaemic", "icd11_code": "BA41", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00014", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0015", "chronic_or_acute": "Acute", "diagnosis_category": "Cardiovascular", "diagnosis": "Acute myocardial infarction", "common_name": "Acute myocardial infarction", "synonyms": "Acute myocardial infarction, Acute", "icd11_code": "BA40.0", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00015", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0016", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Ischemic stroke", "common_name": "Ischemic stroke", "synonyms": "Ischemic stroke, Ischemic", "icd11_code": "BD10", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00016", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0017", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Hemorrhagic stroke", "common_name": "Hemorrhagic stroke", "synonyms": "Hemorrhagic stroke, Hemorrhagic", "icd11_code": "BD11", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00017", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0018", "chronic_or_acute": "Acute", "diagnosis_category": "Cardiovascular", "diagnosis": "Heart failure", "common_name": "Heart failure", "synonyms": "Heart failure, Heart", "icd11_code": "BD56", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00018", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0019", "chronic_or_acute": "Acute", "diagnosis_category": "Respiratory", "diagnosis": "Acute upper respiratory infection", "common_name": "Acute upper respiratory infection", "synonyms": "Acute upper respiratory infection, Acute", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00019", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0020", "chronic_or_acute": "Acute", "diagnosis_category": "Respiratory", "diagnosis": "Community-acquired pneumonia", "common_name": "Community-acquired pneumonia", "synonyms": "Community-acquired pneumonia, Community-acquired", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00020", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0021", "chronic_or_acute": "Chronic", "diagnosis_category": "Respiratory", "diagnosis": "Chronic obstructive pulmonary disease", "common_name": "COPD", "synonyms": "COPD, Chronic obstructive pulmonary disease", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00021", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0022", "chronic_or_acute": "Chronic", "diagnosis_category": "Respiratory", "diagnosis": "Asthma", "common_name": "Asthma", "synonyms": "Asthma", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00022", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0023", "chronic_or_acute": "Acute", "diagnosis_category": "Respiratory", "diagnosis": "Acute bronchitis", "common_name": "Acute bronchitis", "synonyms": "Acute bronchitis, Bronchitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00023", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0024", "chronic_or_acute": "Acute", "diagnosis_category": "Gastrointestinal", "diagnosis": "Acute gastroenteritis", "common_name": "Acute gastroenteritis", "synonyms": "Acute gastroenteritis, Gastroenteritis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00024", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0025", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Gastroesophageal reflux disease", "common_name": "GERD", "synonyms": "GERD, Gastroesophageal reflux disease", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00025", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0026", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Peptic ulcer disease", "common_name": "Peptic ulcer disease", "synonyms": "Peptic ulcer disease, Peptic ulcer", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00026", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0027", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Irritable bowel syndrome", "common_name": "IBS", "synonyms": "IBS, Irritable bowel syndrome", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00027", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0028", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Chronic liver disease", "common_name": "Chronic liver disease", "synonyms": "Chronic liver disease, Liver disease", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00028", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0029", "chronic_or_acute": "Acute", "diagnosis_category": "Gastrointestinal", "diagnosis": "Acute hepatitis", "common_name": "Acute hepatitis", "synonyms": "Acute hepatitis, Hepatitis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00029", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0030", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Chronic hepatitis B", "common_name": "Chronic hepatitis B", "synonyms": "Chronic hepatitis B, Hepatitis B", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00030", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0031", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Chronic hepatitis C", "common_name": "Chronic hepatitis C", "synonyms": "Chronic hepatitis C, Hepatitis C", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00031", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0032", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Cirrhosis of liver", "common_name": "Cirrhosis of liver", "synonyms": "Cirrhosis of liver, Cirrhosis", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00032", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0033", "chronic_or_acute": "Acute", "diagnosis_category": "Gastrointestinal", "diagnosis": "Acute pancreatitis", "common_name": "Acute pancreatitis", "synonyms": "Acute pancreatitis, Pancreatitis", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00033", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0034", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Chronic pancreatitis", "common_name": "Chronic pancreatitis", "synonyms": "Chronic pancreatitis, Pancreatitis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00034", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0035", "chronic_or_acute": "Acute", "diagnosis_category": "Gastrointestinal", "diagnosis": "Acute cholecystitis", "common_name": "Acute cholecystitis", "synonyms": "Acute cholecystitis, Cholecystitis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00035", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0036", "chronic_or_acute": "Chronic", "diagnosis_category": "Gastrointestinal", "diagnosis": "Cholelithiasis", "common_name": "Cholelithiasis", "synonyms": "Cholelithiasis, Gallstones", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00036", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0037", "chronic_or_acute": "Acute", "diagnosis_category": "Genitourinary", "diagnosis": "Urinary tract infection", "common_name": "UTI", "synonyms": "UTI, Urinary tract infection", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00037", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0038", "chronic_or_acute": "Chronic", "diagnosis_category": "Genitourinary", "diagnosis": "Chronic kidney disease", "common_name": "CKD", "synonyms": "CKD, Chronic kidney disease", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00038", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0039", "chronic_or_acute": "Acute", "diagnosis_category": "Genitourinary", "diagnosis": "Acute kidney injury", "common_name": "AKI", "synonyms": "AKI, Acute kidney injury", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00039", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0040", "chronic_or_acute": "Chronic", "diagnosis_category": "Genitourinary", "diagnosis": "Nephrolithiasis", "common_name": "Kidney stones", "synonyms": "Kidney stones, Nephrolithiasis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00040", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0041", "chronic_or_acute": "Chronic", "diagnosis_category": "Genitourinary", "diagnosis": "Benign prostatic hyperplasia", "common_name": "BPH", "synonyms": "BPH, Benign prostatic hyperplasia", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00041", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0042", "chronic_or_acute": "Chronic", "diagnosis_category": "Hematology", "diagnosis": "Iron deficiency anemia", "common_name": "Iron deficiency anemia", "synonyms": "Iron deficiency anemia, Anemia", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00042", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0043", "chronic_or_acute": "Chronic", "diagnosis_category": "Hematology", "diagnosis": "Vitamin B12 deficiency anemia", "common_name": "Vitamin B12 deficiency anemia", "synonyms": "Vitamin B12 deficiency anemia, B12 deficiency", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00043", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0044", "chronic_or_acute": "Chronic", "diagnosis_category": "Hematology", "diagnosis": "Thalassemia", "common_name": "Thalassemia", "synonyms": "Thalassemia", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00044", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0045", "chronic_or_acute": "Chronic", "diagnosis_category": "Musculoskeletal", "diagnosis": "Osteoarthritis", "common_name": "Osteoarthritis", "synonyms": "Osteoarthritis, OA", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00045", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0046", "chronic_or_acute": "Chronic", "diagnosis_category": "Musculoskeletal", "diagnosis": "Rheumatoid arthritis", "common_name": "Rheumatoid arthritis", "synonyms": "Rheumatoid arthritis, RA", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00046", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0047", "chronic_or_acute": "Chronic", "diagnosis_category": "Musculoskeletal", "diagnosis": "Gout", "common_name": "Gout", "synonyms": "Gout", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00047", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0048", "chronic_or_acute": "Chronic", "diagnosis_category": "Musculoskeletal", "diagnosis": "Osteoporosis", "common_name": "Osteoporosis", "synonyms": "Osteoporosis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00048", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0049", "chronic_or_acute": "Chronic", "diagnosis_category": "Musculoskeletal", "diagnosis": "Low back pain", "common_name": "Low back pain", "synonyms": "Low back pain, LBP", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00049", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0050", "chronic_or_acute": "Chronic", "diagnosis_category": "Dermatology", "diagnosis": "Psoriasis", "common_name": "Psoriasis", "synonyms": "Psoriasis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00050", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        # Row 51-100
        {"diagnosis_code": "DIAG-0051", "chronic_or_acute": "Chronic", "diagnosis_category": "Dermatology", "diagnosis": "Eczema", "common_name": "Eczema", "synonyms": "Eczema, Atopic dermatitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00051", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0052", "chronic_or_acute": "Acute", "diagnosis_category": "Dermatology", "diagnosis": "Cellulitis", "common_name": "Cellulitis", "synonyms": "Cellulitis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00052", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0053", "chronic_or_acute": "Acute", "diagnosis_category": "Dermatology", "diagnosis": "Herpes zoster", "common_name": "Shingles", "synonyms": "Shingles, Herpes zoster", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00053", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0054", "chronic_or_acute": "Chronic", "diagnosis_category": "Dermatology", "diagnosis": "Acne vulgaris", "common_name": "Acne", "synonyms": "Acne, Acne vulgaris", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00054", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0055", "chronic_or_acute": "Chronic", "diagnosis_category": "Dermatology", "diagnosis": "Vitiligo", "common_name": "Vitiligo", "synonyms": "Vitiligo", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00055", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0056", "chronic_or_acute": "Acute", "diagnosis_category": "Dermatology", "diagnosis": "Urticaria", "common_name": "Hives", "synonyms": "Hives, Urticaria", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00056", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0057", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Epilepsy", "common_name": "Epilepsy", "synonyms": "Epilepsy, Seizure disorder", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00057", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0058", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Parkinson disease", "common_name": "Parkinson disease", "synonyms": "Parkinson disease, Parkinsonism", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00058", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0059", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Alzheimer disease", "common_name": "Alzheimer disease", "synonyms": "Alzheimer disease, Dementia", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00059", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0060", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Migraine", "common_name": "Migraine", "synonyms": "Migraine", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00060", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0061", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Peripheral neuropathy", "common_name": "Peripheral neuropathy", "synonyms": "Peripheral neuropathy, Neuropathy", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00061", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0062", "chronic_or_acute": "Chronic", "diagnosis_category": "Psychiatry", "diagnosis": "Major depressive disorder", "common_name": "Depression", "synonyms": "Depression, Major depressive disorder", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00062", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0063", "chronic_or_acute": "Chronic", "diagnosis_category": "Psychiatry", "diagnosis": "Generalized anxiety disorder", "common_name": "Anxiety", "synonyms": "Anxiety, Generalized anxiety disorder", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00063", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0064", "chronic_or_acute": "Chronic", "diagnosis_category": "Psychiatry", "diagnosis": "Bipolar disorder", "common_name": "Bipolar disorder", "synonyms": "Bipolar disorder", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00064", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0065", "chronic_or_acute": "Chronic", "diagnosis_category": "Psychiatry", "diagnosis": "Schizophrenia", "common_name": "Schizophrenia", "synonyms": "Schizophrenia", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00065", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0066", "chronic_or_acute": "Chronic", "diagnosis_category": "Psychiatry", "diagnosis": "Insomnia", "common_name": "Insomnia", "synonyms": "Insomnia, Sleep disorder", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00066", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0067", "chronic_or_acute": "Chronic", "diagnosis_category": "Ophthalmology", "diagnosis": "Cataract", "common_name": "Cataract", "synonyms": "Cataract", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00067", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0068", "chronic_or_acute": "Chronic", "diagnosis_category": "Ophthalmology", "diagnosis": "Glaucoma", "common_name": "Glaucoma", "synonyms": "Glaucoma", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00068", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0069", "chronic_or_acute": "Chronic", "diagnosis_category": "Ophthalmology", "diagnosis": "Diabetic retinopathy", "common_name": "Diabetic retinopathy", "synonyms": "Diabetic retinopathy", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00069", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0070", "chronic_or_acute": "Acute", "diagnosis_category": "Ophthalmology", "diagnosis": "Conjunctivitis", "common_name": "Pink eye", "synonyms": "Pink eye, Conjunctivitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00070", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0071", "chronic_or_acute": "Chronic", "diagnosis_category": "Ophthalmology", "diagnosis": "Age-related macular degeneration", "common_name": "AMD", "synonyms": "AMD, Age-related macular degeneration", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00071", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0072", "chronic_or_acute": "Chronic", "diagnosis_category": "ENT", "diagnosis": "Allergic rhinitis", "common_name": "Hay fever", "synonyms": "Hay fever, Allergic rhinitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00072", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0073", "chronic_or_acute": "Chronic", "diagnosis_category": "ENT", "diagnosis": "Chronic sinusitis", "common_name": "Chronic sinusitis", "synonyms": "Chronic sinusitis, Sinusitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00073", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0074", "chronic_or_acute": "Acute", "diagnosis_category": "ENT", "diagnosis": "Acute otitis media", "common_name": "Ear infection", "synonyms": "Ear infection, Acute otitis media", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00074", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0075", "chronic_or_acute": "Chronic", "diagnosis_category": "ENT", "diagnosis": "Hearing loss", "common_name": "Hearing loss", "synonyms": "Hearing loss, Deafness", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00075", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0076", "chronic_or_acute": "Chronic", "diagnosis_category": "ENT", "diagnosis": "Tinnitus", "common_name": "Tinnitus", "synonyms": "Tinnitus, Ringing in ears", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00076", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0077", "chronic_or_acute": "Acute", "diagnosis_category": "ENT", "diagnosis": "Acute pharyngitis", "common_name": "Sore throat", "synonyms": "Sore throat, Acute pharyngitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00077", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0078", "chronic_or_acute": "Acute", "diagnosis_category": "ENT", "diagnosis": "Acute tonsillitis", "common_name": "Tonsillitis", "synonyms": "Tonsillitis, Acute tonsillitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00078", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0079", "chronic_or_acute": "Chronic", "diagnosis_category": "Oral/Dental", "diagnosis": "Dental caries", "common_name": "Tooth decay", "synonyms": "Tooth decay, Dental caries, Cavities", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00079", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0080", "chronic_or_acute": "Chronic", "diagnosis_category": "Oral/Dental", "diagnosis": "Periodontitis", "common_name": "Gum disease", "synonyms": "Gum disease, Periodontitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00080", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0081", "chronic_or_acute": "Chronic", "diagnosis_category": "Oral/Dental", "diagnosis": "Oral submucous fibrosis", "common_name": "OSMF", "synonyms": "OSMF, Oral submucous fibrosis", "department": "Photo Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00081", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0082", "chronic_or_acute": "Chronic", "diagnosis_category": "Oral/Dental", "diagnosis": "Leukoplakia", "common_name": "Leukoplakia", "synonyms": "Leukoplakia", "department": "Photo Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00082", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0083", "chronic_or_acute": "Chronic", "diagnosis_category": "Medical Disease", "diagnosis": "Tension headache", "common_name": "Tension headache", "synonyms": "Tension headache, Tension", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00085", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0084", "chronic_or_acute": "Chronic", "diagnosis_category": "Medical Disease", "diagnosis": "Cluster headache", "common_name": "Cluster headache", "synonyms": "Cluster headache, Cluster", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00086", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0085", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Sciatica", "common_name": "Sciatica", "synonyms": "Sciatica", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00087", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0086", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Cervical spondylosis", "common_name": "Cervical spondylosis", "synonyms": "Cervical spondylosis, Cervical", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00088", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0087", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Lumbar spondylosis", "common_name": "Lumbar spondylosis", "synonyms": "Lumbar spondylosis, Lumbar", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00089", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0088", "chronic_or_acute": "Chronic", "diagnosis_category": "Neurology", "diagnosis": "Carpal tunnel syndrome", "common_name": "Carpal tunnel syndrome", "synonyms": "Carpal tunnel syndrome, Carpal", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00090", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0089", "chronic_or_acute": "Chronic", "diagnosis_category": "Orthopedics", "diagnosis": "Tendinitis", "common_name": "Tendinitis", "synonyms": "Tendinitis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00091", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0090", "chronic_or_acute": "Chronic", "diagnosis_category": "Orthopedics", "diagnosis": "Plantar fasciitis", "common_name": "Plantar fasciitis", "synonyms": "Plantar fasciitis, Plantar", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00092", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0091", "chronic_or_acute": "Chronic", "diagnosis_category": "Orthopedics", "diagnosis": "Achilles tendinitis", "common_name": "Achilles tendinitis", "synonyms": "Achilles tendinitis, Achilles", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00093", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0092", "chronic_or_acute": "Chronic", "diagnosis_category": "Orthopedics", "diagnosis": "Shoulder impingement", "common_name": "Shoulder impingement", "synonyms": "Shoulder impingement, Shoulder", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00094", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0093", "chronic_or_acute": "Chronic", "diagnosis_category": "Orthopedics", "diagnosis": "Rotator cuff tear", "common_name": "Rotator cuff tear", "synonyms": "Rotator cuff tear, Rotator", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00095", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0094", "chronic_or_acute": "Chronic", "diagnosis_category": "Orthopedics", "diagnosis": "Frozen shoulder", "common_name": "Frozen shoulder", "synonyms": "Frozen shoulder, Frozen", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00096", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0096", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Hyperlipidemia", "common_name": "Hyperlipidemia", "synonyms": "Hyperlipidemia", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00098", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0097", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Metabolic syndrome", "common_name": "Metabolic syndrome", "synonyms": "Metabolic syndrome, Metabolic", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00099", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0098", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Vitamin D deficiency", "common_name": "Vitamin D deficiency", "synonyms": "Vitamin D deficiency, Vitamin", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00100", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0099", "chronic_or_acute": "Chronic", "diagnosis_category": "Endocrine/Metabolic", "diagnosis": "Vitamin B12 deficiency", "common_name": "Vitamin B12 deficiency", "synonyms": "Vitamin B12 deficiency, Vitamin", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00101", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        # Row 100-150
        {"diagnosis_code": "DIAG-0100", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Breast cancer", "common_name": "Breast cancer", "synonyms": "Breast cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00102", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0101", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Lung cancer", "common_name": "Lung cancer", "synonyms": "Lung cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00103", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0102", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Colorectal cancer", "common_name": "Colorectal cancer", "synonyms": "Colorectal cancer, Colon cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00104", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0103", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Prostate cancer", "common_name": "Prostate cancer", "synonyms": "Prostate cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00105", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0104", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Cervical cancer", "common_name": "Cervical cancer", "synonyms": "Cervical cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00106", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0105", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Oral cancer", "common_name": "Oral cancer", "synonyms": "Oral cancer, Mouth cancer", "department": "Photo Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00107", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0106", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Stomach cancer", "common_name": "Stomach cancer", "synonyms": "Stomach cancer, Gastric cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00108", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0107", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Liver cancer", "common_name": "Liver cancer", "synonyms": "Liver cancer, Hepatocellular carcinoma", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00109", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0108", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Pancreatic cancer", "common_name": "Pancreatic cancer", "synonyms": "Pancreatic cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00110", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0109", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Leukemia", "common_name": "Leukemia", "synonyms": "Leukemia, Blood cancer", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00111", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0110", "chronic_or_acute": "Chronic", "diagnosis_category": "Oncology", "diagnosis": "Lymphoma", "common_name": "Lymphoma", "synonyms": "Lymphoma", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00112", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0111", "chronic_or_acute": "Chronic", "diagnosis_category": "Gynecology", "diagnosis": "Polycystic ovary syndrome", "common_name": "PCOS", "synonyms": "PCOS, Polycystic ovary syndrome", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00113", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0112", "chronic_or_acute": "Chronic", "diagnosis_category": "Gynecology", "diagnosis": "Endometriosis", "common_name": "Endometriosis", "synonyms": "Endometriosis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00114", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0113", "chronic_or_acute": "Chronic", "diagnosis_category": "Gynecology", "diagnosis": "Uterine fibroids", "common_name": "Uterine fibroids", "synonyms": "Uterine fibroids, Fibroids", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00115", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0114", "chronic_or_acute": "Acute", "diagnosis_category": "Gynecology", "diagnosis": "Pelvic inflammatory disease", "common_name": "PID", "synonyms": "PID, Pelvic inflammatory disease", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00116", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0115", "chronic_or_acute": "Chronic", "diagnosis_category": "Gynecology", "diagnosis": "Menopause", "common_name": "Menopause", "synonyms": "Menopause", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00117", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0116", "chronic_or_acute": "Chronic", "diagnosis_category": "Pediatrics", "diagnosis": "Attention deficit hyperactivity disorder", "common_name": "ADHD", "synonyms": "ADHD, Attention deficit hyperactivity disorder", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00118", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0117", "chronic_or_acute": "Chronic", "diagnosis_category": "Pediatrics", "diagnosis": "Autism spectrum disorder", "common_name": "Autism", "synonyms": "Autism, Autism spectrum disorder", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00119", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0118", "chronic_or_acute": "Acute", "diagnosis_category": "Pediatrics", "diagnosis": "Measles", "common_name": "Measles", "synonyms": "Measles", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00120", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0119", "chronic_or_acute": "Acute", "diagnosis_category": "Pediatrics", "diagnosis": "Chickenpox", "common_name": "Chickenpox", "synonyms": "Chickenpox, Varicella", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00121", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0120", "chronic_or_acute": "Acute", "diagnosis_category": "Pediatrics", "diagnosis": "Mumps", "common_name": "Mumps", "synonyms": "Mumps", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00122", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0121", "chronic_or_acute": "Acute", "diagnosis_category": "Pediatrics", "diagnosis": "Rubella", "common_name": "German measles", "synonyms": "German measles, Rubella", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00123", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0122", "chronic_or_acute": "Acute", "diagnosis_category": "Pediatrics", "diagnosis": "Whooping cough", "common_name": "Pertussis", "synonyms": "Pertussis, Whooping cough", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00124", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0123", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "HIV/AIDS", "common_name": "HIV/AIDS", "synonyms": "HIV/AIDS, HIV", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 30, "billing_code": "BL-00125", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0124", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Sexually transmitted infection", "common_name": "STI", "synonyms": "STI, Sexually transmitted infection", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00126", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0125", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Gonorrhea", "common_name": "Gonorrhea", "synonyms": "Gonorrhea", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00127", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0126", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Syphilis", "common_name": "Syphilis", "synonyms": "Syphilis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00128", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0127", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Chlamydia", "common_name": "Chlamydia", "synonyms": "Chlamydia", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00129", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0128", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Herpes simplex", "common_name": "Herpes", "synonyms": "Herpes, Herpes simplex", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00130", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0129", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Scabies", "common_name": "Scabies", "synonyms": "Scabies", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00131", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0130", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Fungal infection", "common_name": "Fungal infection", "synonyms": "Fungal infection, Mycosis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00132", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0131", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Ringworm", "common_name": "Ringworm", "synonyms": "Ringworm, Tinea", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00133", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0132", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Candidiasis", "common_name": "Yeast infection", "synonyms": "Yeast infection, Candidiasis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 7, "billing_code": "BL-00134", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0133", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Sepsis", "common_name": "Sepsis", "synonyms": "Sepsis, Blood poisoning", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00135", "status": "Approved", "is_reportable": 1, "notifiable": 0},
        {"diagnosis_code": "DIAG-0134", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Meningitis", "common_name": "Meningitis", "synonyms": "Meningitis", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00136", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0135", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Encephalitis", "common_name": "Encephalitis", "synonyms": "Encephalitis, Brain infection", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00137", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0136", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Tetanus", "common_name": "Tetanus", "synonyms": "Tetanus, Lockjaw", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00138", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0137", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Rabies", "common_name": "Rabies", "synonyms": "Rabies", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00139", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0138", "chronic_or_acute": "Chronic", "diagnosis_category": "Infectious Disease", "diagnosis": "Leprosy", "common_name": "Leprosy", "synonyms": "Leprosy, Hansen disease", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00140", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0139", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Chikungunya", "common_name": "Chikungunya", "synonyms": "Chikungunya", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 7, "billing_code": "BL-00141", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0140", "chronic_or_acute": "Acute", "diagnosis_category": "Infectious Disease", "diagnosis": "Japanese encephalitis", "common_name": "Japanese encephalitis", "synonyms": "Japanese encephalitis, JE", "department": "General Medicine", "severity": "Severe", "default_follow_up_days": 7, "billing_code": "BL-00142", "status": "Approved", "is_reportable": 1, "notifiable": 1},
        {"diagnosis_code": "DIAG-0141", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Systemic lupus erythematosus", "common_name": "Lupus", "synonyms": "Lupus, SLE", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00143", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0142", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Multiple sclerosis", "common_name": "MS", "synonyms": "MS, Multiple sclerosis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00144", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0143", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Sjogren syndrome", "common_name": "Sjogren syndrome", "synonyms": "Sjogren syndrome", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00145", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0144", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Scleroderma", "common_name": "Scleroderma", "synonyms": "Scleroderma", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00146", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0145", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Celiac disease", "common_name": "Celiac disease", "synonyms": "Celiac disease, Gluten intolerance", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00147", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0146", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Crohn disease", "common_name": "Crohn disease", "synonyms": "Crohn disease", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00148", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0147", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Ulcerative colitis", "common_name": "Ulcerative colitis", "synonyms": "Ulcerative colitis, UC", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00149", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0148", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Hashimoto thyroiditis", "common_name": "Hashimoto thyroiditis", "synonyms": "Hashimoto thyroiditis", "department": "General Medicine", "severity": "Mild", "default_follow_up_days": 30, "billing_code": "BL-00150", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0149", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Graves disease", "common_name": "Graves disease", "synonyms": "Graves disease", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00151", "status": "Approved", "is_reportable": 0, "notifiable": 0},
        {"diagnosis_code": "DIAG-0150", "chronic_or_acute": "Chronic", "diagnosis_category": "Autoimmune", "diagnosis": "Myasthenia gravis", "common_name": "Myasthenia gravis", "synonyms": "Myasthenia gravis", "department": "General Medicine", "severity": "Moderate", "default_follow_up_days": 30, "billing_code": "BL-00152", "status": "Approved", "is_reportable": 0, "notifiable": 0},
    ]
    
    # Combine all parts
    return part1 + get_data_part2() + get_data_part3()
